### ISSUE TITLE
Generalization to arbitrary libraries?

### ISSUE THREAD

**Issue by turbolent** [pguyot/mbedtls-NewtonOS#1]
Great work on porting mbedtls to the Newton! 

Would it be possible to generalize this work for arbitrary libraries, in particular the `NewtonRuntime` portion?

I have been working on porting newer software to older systems by [compiling WebAssembly to C](https://github.com/turbolent/w2c2), which e.g. [allowed me to run Rust and Swift programs on Mac OS X/PowerPC](https://twitter.com/turbolent/status/1485439938946420736). I'd love to get them running on a Newton, especially Swift :-)

**Comment by pguyot** [comment]
Yes it can be generalized to other libraries.

Here are the current limitations:
- you need to provide required libc/posix/external functions like NewtonRuntime does
- the available memory is very low (so you should focus on embedded libraries, even mbedtls doesn't really work on real hardware except MP2100)
- you cannot have global variables (I think, I don't remember exactly what I eventually did with mbedtls, I had a prototype using a trick at some point though).

This relies on another project developed at the same time, the DCL toolchain.

See https://github.com/pguyot/DCL/blob/master/Sample_Code/ToolchainUtils/README.md

Let's move the conversation there.

**Comment by turbolent** [comment]
@pguyot Thanks for sharing more information and linking to the DCL repo. That repository has issues disabled, and doesn't have discussions enabled either, so I can't ask there: 

I looked at https://github.com/pguyot/DCL/tree/master/Sample_Code/ToolchainUtils/examples, and was wondering if the setup there assumes that the native code is shipped in one package, and then the UI portion is NewtonScript, in a separate package, and calls the functions of the native package?

It would be tremendously helpful if there was a "Hello, world!" example that has both NewtonScript UI + native code function (maybe the example already does it, I'm very new to Newton development, so please excuse the questions)
